# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tcx5--0so-oOzUjHFcQiicWP4CfXpMwy
"""

# ===============================
# INSTALL
# ===============================
!pip install yfinance pandas numpy statsmodels scikit-learn matplotlib

import yfinance as yf
import pandas as pd
import numpy as np
import statsmodels.api as sm
from sklearn.impute import SimpleImputer
import matplotlib.pyplot as plt

np.random.seed(42)

# ===============================
# STOCK UNIVERSE
# ===============================
tickers = [
    "AAPL", "MSFT", "GOOGL", "AMZN", "META",
    "JPM", "GS", "TSLA", "NVDA", "UNH"
]

# ===============================
# DOWNLOAD PRICES
# ===============================
prices = yf.download(
    tickers,
    start="2018-01-01",
    auto_adjust=True,
    progress=False
)["Close"]

prices = prices.dropna(axis=1, thresh=int(0.9 * len(prices)))
prices = prices.ffill().dropna()

returns = prices.pct_change().dropna()

# ===============================
# BACKTEST PARAMETERS
# ===============================
rebalance_freq = 21   # monthly
lookback = 252        # 12 months

portfolio_returns = []

# ===============================
# BACKTEST LOOP
# ===============================
for t in range(lookback + rebalance_freq, len(prices), rebalance_freq):

    price_window = prices.iloc[:t]
    return_window = returns.iloc[:t]

    # -------------------------------
    # Factors
    # -------------------------------
    momentum = price_window.pct_change(lookback).shift(21).iloc[-1]
    volatility = return_window.rolling(lookback).std().iloc[-1] * np.sqrt(252)

    value = {}
    for stock in price_window.columns:
        info = yf.Ticker(stock).info
        eps = info.get("trailingEps", np.nan)
        price = price_window[stock].iloc[-1]
        value[stock] = eps / price if eps and eps > 0 else np.nan

    factors = pd.DataFrame({
        "Value": pd.Series(value),
        "Momentum": momentum,
        "Volatility": volatility
    })

    # -------------------------------
    # FIX: handle NaNs
    # -------------------------------
    factors = factors.fillna(0)  # replace columns that are all NaN
    factors = pd.DataFrame(
        SimpleImputer(strategy="mean").fit_transform(factors),
        columns=factors.columns,
        index=factors.index
    )

    # Standardise
    factors = (factors - factors.mean()) / factors.std()

    # -------------------------------
    # Future returns
    # -------------------------------
    future = returns.iloc[t:t+rebalance_freq].mean()
    data = factors.join(future.rename("FutureReturn")).dropna()

    # Skip period if no valid data
    if data.empty:
        continue

    X = sm.add_constant(data[["Value", "Momentum", "Volatility"]])
    y = data["FutureReturn"]
    model = sm.OLS(y, X).fit()

    # -------------------------------
    # Portfolio construction
    # -------------------------------
    preds = model.predict(X)
    cutoff = preds.quantile(0.7)
    longs = preds[preds >= cutoff].index
    period_return = future[longs].mean()
    portfolio_returns.append(period_return)

# ===============================
# PERFORMANCE METRICS
# ===============================
portfolio_returns = pd.Series(portfolio_returns)
cumulative = (1 + portfolio_returns).cumprod()
sharpe = (portfolio_returns.mean() / portfolio_returns.std()) * np.sqrt(12)

print(f"Sharpe Ratio: {sharpe:.2f}")

# ===============================
# PLOT CUMULATIVE RETURNS
# ===============================
plt.figure(figsize=(10,5))
plt.plot(cumulative)
plt.title("Cumulative Portfolio Returns")
plt.xlabel("Rebalance Period")
plt.ylabel("Cumulative Return")
plt.grid(True)
plt.show()