# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qLLpXf8oV8BSo6Q_J1o_Icu7wLYTqFOX
"""

# ===============================
# INSTALL
# ===============================
!pip install yfinance pandas numpy statsmodels scikit-learn

import yfinance as yf
import pandas as pd
import numpy as np
import statsmodels.api as sm
from sklearn.impute import SimpleImputer

np.random.seed(42)

# ===============================
# STOCK UNIVERSE
# ===============================
tickers = [
    "AAPL", "MSFT", "GOOGL", "AMZN", "META",
    "JPM", "GS", "TSLA", "NVDA", "UNH"
]

# ===============================
# DOWNLOAD PRICES
# ===============================
prices = yf.download(
    tickers,
    start="2021-01-01",
    auto_adjust=True,
    progress=False
)["Close"]

# Drop assets with too much missing data
prices = prices.dropna(axis=1, thresh=int(0.9 * len(prices)))

# Fill small gaps
prices = prices.ffill().dropna()

# ===============================
# RETURNS
# ===============================
returns = prices.pct_change().dropna()

# ===============================
# FACTORS
# ===============================

# Momentum: 12m return, skip last month
momentum = prices.pct_change(252).shift(21)

# Volatility: rolling annualised
volatility = returns.rolling(252).std() * np.sqrt(252)

# Value: Earnings / Price
value = {}
for t in prices.columns:
    stock = yf.Ticker(t)
    eps = stock.info.get("trailingEps", np.nan)
    price = prices[t].iloc[-1]
    value[t] = eps / price if eps and eps > 0 else np.nan

value = pd.Series(value)

# ===============================
# TIME ALIGNMENT
# ===============================
common_index = momentum.index.intersection(volatility.index)

momentum = momentum.loc[common_index].iloc[-1]
volatility = volatility.loc[common_index].iloc[-1]

factors = pd.DataFrame({
    "Value": value,
    "Momentum": momentum,
    "Volatility": volatility
})

# ===============================
# IMPUTATION
# ===============================
imputer = SimpleImputer(strategy="mean")

factors = pd.DataFrame(
    imputer.fit_transform(factors),
    columns=factors.columns,
    index=factors.index
)

# ===============================
# STANDARDISE
# ===============================
factors = (factors - factors.mean()) / factors.std()

# ===============================
# TARGET VARIABLE
# ===============================
future_returns = returns.shift(-21).mean()
future_returns = future_returns.loc[factors.index]

data = factors.join(future_returns.rename("FutureReturn")).dropna()

X = sm.add_constant(data[["Value", "Momentum", "Volatility"]])
y = data["FutureReturn"]

# ===============================
# REGRESSION
# ===============================
model = sm.OLS(y, X).fit()
print(model.summary())

# ===============================
# PORTFOLIO
# ===============================
expected_returns = model.predict(X)

portfolio = pd.DataFrame({
    "Expected Return": expected_returns
}).sort_values("Expected Return", ascending=False)

portfolio["Weight"] = 1 / len(portfolio)

portfolio